export {default as Navbar} from './navbar.svelte'
export {default as HomeHero} from './home-hero.svelte'
export {default as Content} from './content.svelte'
export {default as About} from './about.svelte'
export {default as Footer} from './footer.svelte'